### PR TITLE
Description fix

### PR DESCRIPTION
**Pull request by rnavarro**
Hey There,

I saw your cool project but I noticed that the descriptions were a little weird looking. I found and fixed the bug that was causing that and I also took the liberty to PEP8 your code a bit.

Have a look at the pull request and let me know what you think!

### CODE REVIEW

**Review by jusung806 — COMMENTED** [review]
The movie description is written specifically in that format so that it is in pep 8 standard

**Comment by rnavarro** [comment]
I noticed that the final output of the description had these weird parenthesis around it:

selection_567

With my fixes it looks like this instead:

selection_568

**Review by jusung806 — COMMENTED** [review]
From Pep8 guidelines a url is discouraged from being broken up.  The comment #NOQA will allow Pep8 to recognize it and allow the characters to go longer in the string.

**Comment by rnavarro** [comment]
Oh I didn't know that, let me fix up the PR then.

**Review by jusung806 — APPROVED** [review]

**Review by jusung806 — APPROVED** [review]

**Review by jusung806 — APPROVED** [review]

**Review by jusung806 — APPROVED** [review]

**Pull request merged**
